import "./global.scss";
import { Metadata } from "next";
import { Nav } from "@/components/atoms/nav";

export const metadata: Metadata = {
	title: {
		default: "Next.js course",
		template: "%s | Hello next project"
	},
	description: "Generated by Next.js"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Nav />
				{children}
			</body>
		</html>
	);
}

